version: '3'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/user/src/app
    ports:
      - 5000:5000
    restart: always
    tty: true

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/user/src/app
    ports:
      - 3000:3000
    depends_on:
      - backend

  proxy:
    build: 
      ./proxy
    volumes:
      - ./proxy:/user/src/app
    ports:
      - "80:80"
    restart: 
      always
    depends_on:
      - backend
      - frontend
  
